const products = [
  {
    id: 'watch-men-1',
    image: './Images/product/product-1.png',
    name: 'Bugatti Luxury Watch - Perfect for Atheletes',
    price: 19000,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae assumenda deserunt doloremque eaque nisi ea natus modi doloribus consectetur qui debitis praesentium eum aspernatur repellat quam, aliquam ab mollitia quos. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla obcaecati perspiciatis, temporibus quidem aut nihil quaerat quod alias, suscipit explicabo veniam ipsa similique neque repudiandae? Dolorem, deserunt! At, saepe cum!',
    dis: 10,
    var1: './Images/product/product-1.png',
    var2: './Images/product/product-1.png',
    var3: './Images/product/product-1.png',
    var4: './Images/product/product-1.png',
    var5: './Images/product/product-1.png',
    var6: './Images/product/product-1.png',
    var7: './Images/product/product-1.png',
    var8: './Images/product/product-1.png',
  },
  {
    id: 'watch-men-2',
    image: './Images/product/product-1.png',
    name: 'Bugatti Luxury Watch - Perfect for Atheletes',
    price: 11000,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae assumenda deserunt doloremque eaque nisi ea natus modi doloribus consectetur qui debitis praesentium eum aspernatur repellat quam, aliquam ab mollitia quos. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla obcaecati perspiciatis, temporibus quidem aut nihil quaerat quod alias, suscipit explicabo veniam ipsa similique neque repudiandae? Dolorem, deserunt! At, saepe cum!',
    dis: 10,
  },
  {
    id: 'watch-men-3',
    image: './Images/product/product-1.png',
    name: 'Bugatti Luxury Watch - Perfect for Atheletes',
    price: 13000,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae assumenda deserunt doloremque eaque nisi ea natus modi doloribus consectetur qui debitis praesentium eum aspernatur repellat quam, aliquam ab mollitia quos. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla obcaecati perspiciatis, temporibus quidem aut nihil quaerat quod alias, suscipit explicabo veniam ipsa similique neque repudiandae? Dolorem, deserunt! At, saepe cum!',
    dis: 10,
  },
  {
    id: 'watch-men-1',
    image: './Images/product/product-1.png',
    name: 'Bugatti Luxury Watch - Perfect for Atheletes',
    price: 19000,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae assumenda deserunt doloremque eaque nisi ea natus modi doloribus consectetur qui debitis praesentium eum aspernatur repellat quam, aliquam ab mollitia quos. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla obcaecati perspiciatis, temporibus quidem aut nihil quaerat quod alias, suscipit explicabo veniam ipsa similique neque repudiandae? Dolorem, deserunt! At, saepe cum!',
    dis: 10,
  },
  {
    id: 'watch-men-2',
    image: './Images/product/product-1.png',
    name: 'Bugatti Luxury Watch - Perfect for Atheletes',
    price: 11000,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae assumenda deserunt doloremque eaque nisi ea natus modi doloribus consectetur qui debitis praesentium eum aspernatur repellat quam, aliquam ab mollitia quos. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla obcaecati perspiciatis, temporibus quidem aut nihil quaerat quod alias, suscipit explicabo veniam ipsa similique neque repudiandae? Dolorem, deserunt! At, saepe cum!',
    dis: 10,
  },
  {
    id: 'watch-men-3',
    image: './Images/product/product-1.png',
    name: 'Bugatti Luxury Watch - Perfect for Atheletes',
    price: 13000,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae assumenda deserunt doloremque eaque nisi ea natus modi doloribus consectetur qui debitis praesentium eum aspernatur repellat quam, aliquam ab mollitia quos. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla obcaecati perspiciatis, temporibus quidem aut nihil quaerat quod alias, suscipit explicabo veniam ipsa similique neque repudiandae? Dolorem, deserunt! At, saepe cum!',
    dis: 10,
  }
]